//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleWebOPC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class OpcUaUser
    {
        public int Id { get; set; }

        [DisplayName("Login")]
        [Required(ErrorMessage ="This field is mandatory")]
        public string Login { get; set; }

        [DisplayName("Password")]
        [Required(ErrorMessage = "This field is mandatory")]
        public string Password { get; set; }

        public string Privilages { get; set; }

        public string TestRow { get; set; }
    }
}
